# TO BE DEPLOYED WITH
# - ingress_demo.yml
# - metrics_demo.yml
---
# 1 -> You should know by now why this is here
# 2 -> where can traefik find this container?
networks:
  loki_net:

version: '3.8'

services:

  loki:
    image: docker.io/grafana/loki:3.3.1

    command:
      - -config.file=/etc/loki/local-config.yaml

    networks:
      prometheus_net:
      loki_net:

    volumes:
      - /data/configs/loki/loki.yml:/etc/loki/local-config.yaml:ro
      - /data/loki:/loki

    deploy:
      replicas: 1
      labels:
        # API-based service discovery for prometheus
        - prometheus.io/scrape-me=yes-please
        - prometheus.io/metrics-path=/metrics
        - prometheus.io/metrics-port=3100

  promtail:
    image: docker.io/grafana/promtail:3.2.2

    command:
      - -config.file=/etc/promtail/config.yml

    networks:
      prometheus_net:
      loki_net:

    volumes:
      - /data/configs/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock  # 1
    deploy:
      mode: global  # yep, logs are on each of our nodes!
      labels:
        # API-based service discovery for prometheus
        - prometheus.io/scrape-me=yes-please
        - prometheus.io/metrics-path=/metrics
        - prometheus.io/metrics-port=9080

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: docker.io/grafana/grafana:11.4.0
    networks:
      loki_net:
      traefik_net:
        aliases:
          - grafana.vcc.internal

    deploy:
      labels:
        - "traefik.enable=true"  # hi traefik, I'm your guy
        - "traefik.docker.network=vcc_traefik_net"  # 2
        - "traefik.http.routers.grafana.rule=Host(`grafana.vcc.internal`)"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
