# TODO https
issuer: https://auth.vcc.internal

storage:
  # TODO use postgres
  type: sqlite3
  config:
    file: /data/dex.db

web:
  http: 0.0.0.0:5556

oauth2:
  grantTypes:
    - authorization_code
  skipApprovalScreen: true
  passwordConnector: local

staticClients:

  # TODO remove
  - id: oauth-debugger
    redirectURIs:
    - 'https://oauthdebugger.com/debug'
    name: 'OAuth debug app'
    secret: bm9uIGF2ZXZpIG5pZW50ZSBkaSBtZWdsaW8gZGEgZmFyZT8K

  # TODO add forgejo client
  # TODO add grafana client

enablePasswordDB: true
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
